org: lmpbarga
app: node-api-test
service: node-api-test
frameworkVersion: "3"

provider:
    name: aws
    runtime: nodejs14.x

functions:
    hello:
        handler: handler.handler
        events:
            - httpApi: "*"

plugins:
    - serverless-offline
